@startuml
enum ItemType {
    Real
    Virtual
}

class Item {
    ItemUUID identifier
    ItemType type
    String staticAssetID
}

Item "1" --- "1" ItemUUID : contains
Item "1" --- "1" ItemType : contains
@enduml
