@startuml
Interface Manager
Interface StorageController {
    + any Query()
    + void Add()
    + void Remove()
    + void Update()
}

enum MarkupType {
    Text
    Highlight
    Line
    Shape
    CustomRaster
    CustomVector
}

struct ArticleMarkup {
    MarkupType type
    string content
}

ArticleMarkup "1" *-- "1" MarkupType : contains

struct Article {
    + string title
    + string content
    + List<ArticleMarkup> markups
}

Article "1" *-- "N" ArticleMarkup : contains

struct BookReview extends Article {
    + Book book
}

class BookReviewManager implements Manager {
    + BookReview RequestQueryBookReview()
    + void RequestAddBookReview()
    + void RequestRemoveBookReview()
    + void RequestUpdateBookReview()
}

BookReviewManager --- BookReview : use
BookReviewManager --- BookReviewStorageController : use

class BookReviewStorageQueryOptimizer {}
class BookReviewStorageController implements StorageController {
    + BookReviewStorageQueryOptimizer optimizer
}
BookReviewStorageController "1" *-- "1" BookReviewStorageQueryOptimizer : contains

BookReviewStorageController --- BookReview : use

' BookReview SubSystem

class BookReviewSubSystem {
    + {static} BookReviewStorageController bookReviewStorageController
    + {static} BookReviewManager bookReviewManager
}
BookReviewSubSystem "1" *-- "1" BookReviewStorageController
BookReviewSubSystem "1" *-- "1" BookReviewManager
@enduml
