@startuml
Interface Manager
Interface StorageController {
    + any Query()
    + void Add()
    + void Remove()
    + void Update()
}

enum BookSuggestionManualRequestType {
    Normal
    NewCategory
    EmotionBased
}
struct BookSuggestionManualRequest {
    + BookSuggestionManualRequestType type
    + string prompt
}
BookSuggestionManualRequest "1" *-- "1" BookSuggestionManualRequestType : contains

struct BookSuggestion {}

class BookSuggestionWorker {}
BookSuggestionWorker --- BookSuggestion : use

class BookSuggestionScheduler {
    + BookSuggestionWorker worker
}

BookSuggestionScheduler "1" *-- "1" BookSuggestionWorker : contains

class BookSuggestionManager implements Manager {
    + {static} void InvokeBookSuggestionManual(BookSuggestionManualRequest req)
}
BookSuggestionManager --- BookSuggestionManualRequest : use
BookSuggestionManager --- BookSuggestionScheduler : use

class BookSuggestionStorageController implements StorageController {}
BookSuggestionStorageController --- BookSuggestion : use

class BookSuggestionSubSystem {
    + {static} BookSuggestionManager bookSuggestionManager
    + {static} BookSuggestionStorageController bookSuggestionStorageController
    + List<BookSuggestionScheduler> bookSuggestionSchedulers
}

BookSuggestionSubSystem "1" *-- "1" BookSuggestionManager : contains
BookSuggestionSubSystem "1" *-- "1" BookSuggestionStorageController : contains
BookSuggestionSubSystem "1" *-- "N" BookSuggestionScheduler : contains

@enduml
