@startuml
Interface Manager
Interface StorageController {
    + any Query()
    + void Add()
    + void Remove()
    + void Update()
}

struct BookSuggestion {}

class BookSuggestionWorker {}
BookSuggestionWorker --- BookSuggestion : use

class BookSuggestionScheduler {
    + BookSuggestionWorker worker
}

BookSuggestionScheduler "1" *-- "1" BookSuggestionWorker : contains

class BookSuggestionManager implements Manager {}
class BookSuggestionStorageController implements StorageController {}
BookSuggestionStorageController --- BookSuggestion : use

class BookSuggestionSubSystem {
    + {static} BookSuggestionManager bookSuggestionManager
    + {static} BookSuggestionStorageController bookSuggestionStorageController
    + List<BookSuggestionScheduler> bookSuggestionSchedulers
}

BookSuggestionSubSystem "1" *-- "1" BookSuggestionManager : contains
BookSuggestionSubSystem "1" *-- "1" BookSuggestionStorageController : contains
BookSuggestionSubSystem "1" *-- "N" BookSuggestionScheduler : contains

@enduml
