@startuml
Interface Manager
Interface StorageController<T> {
    + T Query()
    + void Add()
    + void Remove()
    + void Update()
}

enum MarkupType {
    Text
    Highlight
    Line
    Shape
    CustomRaster
    CustomVector
}

struct ArticleMarkup {
    MarkupType type
    String content
}

ArticleMarkup "1" o-- "1" MarkupType : contains

struct Article {
    + String title
    + String content
    + List<ArticleMarkup> markups
}

Article "1" o-- "N" ArticleMarkup : contains

struct BookReview extends Article {
    + Book book
}

class BookReviewManager implements Manager {
    + BookReview RequestQueryBookReview()
    + void RequestAddBookReview()
    + void RequestRemoveBookReview()
    + void RequestUpdateBookReview()
}

BookReviewManager --- BookReview : use
BookReviewManager --- BookReviewStorageController : use

class BookReviewStorageQueryOptimizer {}
class BookReviewStorageController<T> implements StorageController {
    + BookReviewStorageQueryOptimizer optimizer
}
BookReviewStorageController "1" o-- "1" BookReviewStorageQueryOptimizer : contains

BookReviewStorageController --- BookReview : use

' BookReview SubSystem

class BookReviewSubSystem {
    + {static} BookReviewStorageController bookReviewStorageController
    + {static} BookReviewManager bookReviewManager
}
BookReviewSubSystem "1" o-- "1" BookReviewStorageController : contains
BookReviewSubSystem "1" o-- "1" BookReviewManager : contains
@enduml
