@startuml
Interface Manager
Interface StorageController<T> {
    + T Query()
    + void Add()
    + void Remove()
    + void Update()
}

class Tier {
    + String name
}

struct RatingTierMatch {
    + any[] ratingRange
    + Tier tier
}
RatingTierMatch "1" --- "1" Tier : contains

struct Rating {
    + UserUUID identifier
    + any ratings
}
Rating "1" --- "1" UserUUID : contains

class RatingManager implements Manager {
    + {static} List<RatingTierMatch> ratingTierMatch
    + {static} Rating GetCurrentUserRating()
}
RatingManager "1" --- "N" RatingTierMatch : contains
RatingManager --- User : use
RatingManager --- Rating : use

class RatingStorageController implements StorageController {}
RatingStorageController --- Rating : use

class RatingsSubSystem {
    + {static} RatingManager ratingManager
    + {static} RatingStorageController ratingStorageController
}

RatingsSubSystem "1" o-- "1" RatingManager : contains
RatingsSubSystem "1" o-- "1" RatingStorageController : contains

@enduml
